### PR TITLE
Mutants Optimisations: big-packages, timeout multiplier, stacks-signer case

### PR DESCRIPTION
**Pull request by ASuciuX**
Updates:
1. split big packages into `stackslib` and `stacks-node`
2. update cargo mutants to use specific version from github in order to include a timeout multiplier feature
3. add a specific run case for `stacks-signer`

### CODE REVIEW

**Comment by wileyj** [comment]
can you share an example workflow using these changes?

**Comment by ASuciuX** [comment]
The workflow that works like this PR is the 3rd example.  


Debug runs that showcase the issue that appeared when running `stacks-signer` mutants:
1. Run working with cargo build and cargo nextest run before cargo mutants:
Action run: https://github.com/ASuciuX/stacks-core/actions/runs/7901429286/attempts/2?pr=57
Action file: [https://github.com/stacks-network/actions/blob/8a7cb7ed0249b473d241b57228cd718d2bd1e3ef/stacks-core/mutation-testing/pr-differences/action.yml#L[…]9](https://github.com/stacks-network/actions/blob/8a7cb7ed0249b473d241b57228cd718d2bd1e3ef/stacks-core/mutation-testing/pr-differences/action.yml#L201-L209)
2. Run not working without cargo build and cargo nextest run:
Action run: https://github.com/ASuciuX/stacks-core/actions/runs/7901429286/attempts/3?pr=57
Action file: [https://github.com/stacks-network/actions/blob/801b21e8294c032686dab54b74cb579074141764/stacks-core/mutation-testing/pr-differences/action.yml#L[…]3](https://github.com/stacks-network/actions/blob/801b21e8294c032686dab54b74cb579074141764/stacks-core/mutation-testing/pr-differences/action.yml#L201-L203)
3. Run working trying only cargo nextest run before cargo mutants:
Action run: https://github.com/ASuciuX/stacks-core/actions/runs/7901429286?pr=57
Action file: [https://github.com/stacks-network/actions/blob/b9971c8063623e9f4dee82164652264cce703216/stacks-core/mutation-testing/pr-differences/action.yml#L[…]6](https://github.com/stacks-network/actions/blob/b9971c8063623e9f4dee82164652264cce703216/stacks-core/mutation-testing/pr-differences/action.yml#L201-L206)

**Comment by wileyj** [comment]
> 3\. https://github.com/ASuciuX/stacks-core/actions/runs/7901429286?pr=57

if i understand you here, the link in item 3 is what is being proposed in this change?
can you explain if this specific error is expected? https://github.com/ASuciuX/stacks-core/actions/runs/7901429286/job/21571077307?pr=57#step:2:125

https://github.com/stacks-network/actions/blob/feat/mutation-testing/stacks-core/mutation-testing/output-pr-mutants/action.yml#L65

is being evaluated as:
```
  
  # Check and append the folders that should be uploaded to artifacts for the stacks-node package
  if  == "true"; then
    if  == "true"; then
      for i in {0..3}; do
        folders+=("mutants-shard-stacks-node-$i")
      done
    else
      folders+=("mutants-shard-stacks-node--1")
    fi
  fi
 ```
 
 there may be an issue here: https://github.com/ASuciuX/stacks-core/blob/feat/test-stacks-signer/.github/workflows/pr-differences-mutants.yml#L207

**Comment by wileyj** [comment]
```
Run stacks-network/actions/stacks-core/mutation-testing/output-pr-mutants@feat/mutation-testing
  with:
    stackslib_package: true
    shards_for_stackslib_package: false
    small_packages: true
    shards_for_small_packages: false
    stacks_signer: true
    ```

**Comment by ASuciuX** [comment]
I've had `false` outputs set to those variables before. They added more `if else` statements, and I removed them so now there are only true outputs set, but I can change that if it would more appropriate to have it more verbose ( if there are no mutants on a specific package the output will be empty `` instead of false, which is still different than true ).

#### Also, the runs I've shared before were for specific testing cases from when I was developing them. This would be a final run:

PR https://github.com/ASuciuX/stacks-core/pull/58
Workflow run https://github.com/ASuciuX/stacks-core/actions/runs/7904568232
The workflow timed out as there were too many mutants on stackslib, after I finish fixing the code, I'll start adding skip-mutants headers for timeout functions so this should happen a lot less in the future ( there were a lot of mutants and most of them were timeout ).

**Comment by wileyj** [comment]
> I've had `false` outputs set to those variables before. They added more `if else` statements, and I removed them so now there are only true outputs set, but I can change that if it would more appropriate to have it more verbose ( if there are no mutants on a specific package the output will be empty `` instead of false, which is still different than true ).
> 
> #### Also, the runs I've shared before were for specific testing cases from when I was developing them. This would be a final run:
> PR [ASuciuX/stacks-core#58](https://github.com/ASuciuX/stacks-core/pull/58) Workflow run https://github.com/ASuciuX/stacks-core/actions/runs/7904568232 The workflow timed out as there were too many mutants on stackslib, after I finish fixing the code, I'll start adding skip-mutants headers for timeout functions so this should happen a lot less in the future ( there were a lot of mutants and most of them were timeout ).

same issue here:
https://github.com/ASuciuX/stacks-core/actions/runs/7904568232/job/21587524440#step:2:77
https://github.com/ASuciuX/stacks-core/actions/runs/7904568232/job/21587524440#step:2:78

i'm comfortable merging this when there are specific unhandled script errors

**Comment by ASuciuX** [comment]
> same issue here: https://github.com/ASuciuX/stacks-core/actions/runs/7904568232/job/21587524440#step:2:77 https://github.com/ASuciuX/stacks-core/actions/runs/7904568232/job/21587524440#step:2:78
> 
> i'm comfortable merging this when there are specific unhandled script errors

I changed the action to send false if it's not true. Here's a run with it working: https://github.com/ASuciuX/stacks-core/actions/runs/7901429286/job/21625886921?pr=57#step:2:49

**Review by wileyj — APPROVED** [review]

**Pull request merged**
